@startuml

title __ACTION's Class Diagram__\n

  namespace survival2d {
    namespace match.action {
      interface survival2d.match.action.PlayerAction {
      }
    }
  }
  

  namespace survival2d {
    namespace match.action {
      enum PlayerActionEnum {
        ATTACK
        CHANGE_WEAPON
        MOVE
        actionClass
      }
    }
  }
  

  namespace survival2d {
    namespace match.action {
      class survival2d.match.action.PlayerAttack {
          + PlayerAttack()
      }
    }
  }
  

  namespace survival2d {
    namespace match.action {
      class survival2d.match.action.PlayerChangeWeapon {
          - weaponIndex : int
          + PlayerChangeWeapon()
          {static} + builder()
          + getWeaponIndex()
      }
    }
  }
  

  namespace survival2d {
    namespace match.action {
      class survival2d.match.action.PlayerChangeWeapon.PlayerChangeWeaponBuilder {
          - weaponIndex : int
          + build()
          + toString()
          + weaponIndex()
          ~ PlayerChangeWeaponBuilder()
      }
    }
  }
  

  namespace survival2d {
    namespace match.action {
      class survival2d.match.action.PlayerDropItem {
          ~ itemId : String
          + PlayerDropItem()
          + getItemId()
      }
    }
  }
  

  namespace survival2d {
    namespace match.action {
      class survival2d.match.action.PlayerMove {
          - direction : Vector2D
          - rotation : double
          + PlayerMove()
          {static} + builder()
          + getDirection()
          + getRotation()
      }
    }
  }
  

  namespace survival2d {
    namespace match.action {
      class survival2d.match.action.PlayerMove.PlayerMoveBuilder {
          - direction : Vector2D
          - rotation : double
          + build()
          + direction()
          + rotation()
          + toString()
          ~ PlayerMoveBuilder()
      }
    }
  }
  

  namespace survival2d {
    namespace match.action {
      class survival2d.match.action.PlayerReloadWeapon {
      }
    }
  }
  

  namespace survival2d {
    namespace match.action {
      class survival2d.match.action.PlayerTakeItem {
      }
    }
  }
  

  survival2d.match.action.PlayerAttack .up.|> survival2d.match.action.PlayerAction
  survival2d.match.action.PlayerChangeWeapon .up.|> survival2d.match.action.PlayerAction
  survival2d.match.action.PlayerChangeWeapon +-down- survival2d.match.action.PlayerChangeWeapon.PlayerChangeWeaponBuilder
  survival2d.match.action.PlayerDropItem .up.|> survival2d.match.action.PlayerAction
  survival2d.match.action.PlayerMove .up.|> survival2d.match.action.PlayerAction
  survival2d.match.action.PlayerMove +-down- survival2d.match.action.PlayerMove.PlayerMoveBuilder
  survival2d.match.action.PlayerReloadWeapon .up.|> survival2d.match.action.PlayerAction
  survival2d.match.action.PlayerTakeItem .up.|> survival2d.match.action.PlayerAction


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
