name: Survival2D
console:
  max_message_size_bytes: 409600
database:
  address:
    - "root@127.0.0.1:26257"
#    - "root@127.0.0.1:26257/defaultdb?sslmode=disable"
logger:
  file: "/nakama/data/log.log"
  level: "DEBUG"
  rotation: true
runtime:
  path: "."
  js_entrypoint: "./build/index.js"
session:
  token_expiry_sec: 7200 # 2 hours
socket:
  max_message_size_bytes: 4096 # reserved buffer
  max_request_size_bytes: 131072
