// automatically generated by the FlatBuffers compiler, do not modify

package survival2d.flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class BulletItem extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_1_12_0(); }
  public static BulletItem getRootAsBulletItem(ByteBuffer _bb) { return getRootAsBulletItem(_bb, new BulletItem()); }
  public static BulletItem getRootAsBulletItem(ByteBuffer _bb, BulletItem obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public BulletItem __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String owner() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer ownerAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer ownerInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public survival2d.flatbuffers.Vec2 direction() { return direction(new survival2d.flatbuffers.Vec2()); }
  public survival2d.flatbuffers.Vec2 direction(survival2d.flatbuffers.Vec2 obj) { int o = __offset(6); return o != 0 ? obj.__assign(o + bb_pos, bb) : null; }
  public byte type() { int o = __offset(8); return o != 0 ? bb.get(o + bb_pos) : 0; }

  public static void startBulletItem(FlatBufferBuilder builder) { builder.startTable(3); }
  public static void addOwner(FlatBufferBuilder builder, int ownerOffset) { builder.addOffset(0, ownerOffset, 0); }
  public static void addDirection(FlatBufferBuilder builder, int directionOffset) { builder.addStruct(1, directionOffset, 0); }
  public static void addType(FlatBufferBuilder builder, byte type) { builder.addByte(2, type, 0); }
  public static int endBulletItem(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public BulletItem get(int j) { return get(new BulletItem(), j); }
    public BulletItem get(BulletItem obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

