// automatically generated by the FlatBuffers compiler, do not modify

package survival2d.flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class CreateItemOnMapResponse extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_1_12_0(); }
  public static CreateItemOnMapResponse getRootAsCreateItemOnMapResponse(ByteBuffer _bb) { return getRootAsCreateItemOnMapResponse(_bb, new CreateItemOnMapResponse()); }
  public static CreateItemOnMapResponse getRootAsCreateItemOnMapResponse(ByteBuffer _bb, CreateItemOnMapResponse obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public CreateItemOnMapResponse __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int id() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public byte itemType() { int o = __offset(6); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public Table item(Table obj) { int o = __offset(8); return o != 0 ? __union(obj, o + bb_pos) : null; }
  public survival2d.flatbuffers.Vec2 position() { return position(new survival2d.flatbuffers.Vec2()); }
  public survival2d.flatbuffers.Vec2 position(survival2d.flatbuffers.Vec2 obj) { int o = __offset(10); return o != 0 ? obj.__assign(o + bb_pos, bb) : null; }
  public survival2d.flatbuffers.Vec2 rawPosition() { return rawPosition(new survival2d.flatbuffers.Vec2()); }
  public survival2d.flatbuffers.Vec2 rawPosition(survival2d.flatbuffers.Vec2 obj) { int o = __offset(12); return o != 0 ? obj.__assign(o + bb_pos, bb) : null; }

  public static void startCreateItemOnMapResponse(FlatBufferBuilder builder) { builder.startTable(5); }
  public static void addId(FlatBufferBuilder builder, int id) { builder.addInt(0, id, 0); }
  public static void addItemType(FlatBufferBuilder builder, byte itemType) { builder.addByte(1, itemType, 0); }
  public static void addItem(FlatBufferBuilder builder, int itemOffset) { builder.addOffset(2, itemOffset, 0); }
  public static void addPosition(FlatBufferBuilder builder, int positionOffset) { builder.addStruct(3, positionOffset, 0); }
  public static void addRawPosition(FlatBufferBuilder builder, int rawPositionOffset) { builder.addStruct(4, rawPositionOffset, 0); }
  public static int endCreateItemOnMapResponse(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public CreateItemOnMapResponse get(int j) { return get(new CreateItemOnMapResponse(), j); }
    public CreateItemOnMapResponse get(CreateItemOnMapResponse obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

