// automatically generated by the FlatBuffers compiler, do not modify

package survival2d.flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class CreateItemOnMapResponse extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_1_12_0(); }
  public static CreateItemOnMapResponse getRootAsCreateItemOnMapResponse(ByteBuffer _bb) { return getRootAsCreateItemOnMapResponse(_bb, new CreateItemOnMapResponse()); }
  public static CreateItemOnMapResponse getRootAsCreateItemOnMapResponse(ByteBuffer _bb, CreateItemOnMapResponse obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public CreateItemOnMapResponse __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte itemType() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public Table item(Table obj) { int o = __offset(6); return o != 0 ? __union(obj, o + bb_pos) : null; }

  public static int createCreateItemOnMapResponse(FlatBufferBuilder builder,
      byte item_type,
      int itemOffset) {
    builder.startTable(2);
    CreateItemOnMapResponse.addItem(builder, itemOffset);
    CreateItemOnMapResponse.addItemType(builder, item_type);
    return CreateItemOnMapResponse.endCreateItemOnMapResponse(builder);
  }

  public static void startCreateItemOnMapResponse(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addItemType(FlatBufferBuilder builder, byte itemType) { builder.addByte(0, itemType, 0); }
  public static void addItem(FlatBufferBuilder builder, int itemOffset) { builder.addOffset(1, itemOffset, 0); }
  public static int endCreateItemOnMapResponse(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public CreateItemOnMapResponse get(int j) { return get(new CreateItemOnMapResponse(), j); }
    public CreateItemOnMapResponse get(CreateItemOnMapResponse obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

