// automatically generated by the FlatBuffers compiler, do not modify

package survival2d.flatbuffers;

public final class EntityType {
  private EntityType() { }
  public static final byte NONE = 0;

  public static final String[] names = { "NONE", };

  public static String name(int e) { return names[e]; }
}

