// automatically generated by the FlatBuffers compiler, do not modify

package survival2d.flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class FindMatchResponse extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_1_12_0(); }
  public static FindMatchResponse getRootAsFindMatchResponse(ByteBuffer _bb) { return getRootAsFindMatchResponse(_bb, new FindMatchResponse()); }
  public static FindMatchResponse getRootAsFindMatchResponse(ByteBuffer _bb, FindMatchResponse obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public FindMatchResponse __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int matchId() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }

  public static int createFindMatchResponse(FlatBufferBuilder builder,
      int matchId) {
    builder.startTable(1);
    FindMatchResponse.addMatchId(builder, matchId);
    return FindMatchResponse.endFindMatchResponse(builder);
  }

  public static void startFindMatchResponse(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addMatchId(FlatBufferBuilder builder, int matchId) { builder.addInt(0, matchId, 0); }
  public static int endFindMatchResponse(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public FindMatchResponse get(int j) { return get(new FindMatchResponse(), j); }
    public FindMatchResponse get(FindMatchResponse obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

