// automatically generated by the FlatBuffers compiler, do not modify

package survival2d.flatbuffers;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Table;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class Gun extends Table {
  public static void ValidateVersion() {
    Constants.FLATBUFFERS_1_12_0();
  }

  public static Gun getRootAsGun(ByteBuffer _bb) {
    return getRootAsGun(_bb, new Gun());
  }

  public static Gun getRootAsGun(ByteBuffer _bb, Gun obj) {
    _bb.order(ByteOrder.LITTLE_ENDIAN);
    return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb));
  }

  public static int createGun(FlatBufferBuilder builder, byte type, int remainBullets) {
    builder.startTable(2);
    Gun.addRemainBullets(builder, remainBullets);
    Gun.addType(builder, type);
    return Gun.endGun(builder);
  }

  public static void startGun(FlatBufferBuilder builder) {
    builder.startTable(2);
  }

  public static void addType(FlatBufferBuilder builder, byte type) {
    builder.addByte(0, type, 0);
  }

  public static void addRemainBullets(FlatBufferBuilder builder, int remainBullets) {
    builder.addInt(1, remainBullets, 0);
  }

  public static int endGun(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public void __init(int _i, ByteBuffer _bb) {
    __reset(_i, _bb);
  }

  public Gun __assign(int _i, ByteBuffer _bb) {
    __init(_i, _bb);
    return this;
  }

  public byte type() {
    int o = __offset(4);
    return o != 0 ? bb.get(o + bb_pos) : 0;
  }

  public int remainBullets() {
    int o = __offset(6);
    return o != 0 ? bb.getInt(o + bb_pos) : 0;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) {
      __reset(_vector, _element_size, _bb);
      return this;
    }

    public Gun get(int j) {
      return get(new Gun(), j);
    }

    public Gun get(Gun obj, int j) {
      return obj.__assign(__indirect(__element(j), bb), bb);
    }
  }
}
