// automatically generated by the FlatBuffers compiler, do not modify

package survival2d.flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class GunItemTable extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_1_12_0(); }
  public static GunItemTable getRootAsGunItemTable(ByteBuffer _bb) { return getRootAsGunItemTable(_bb, new GunItemTable()); }
  public static GunItemTable getRootAsGunItemTable(ByteBuffer _bb, GunItemTable obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public GunItemTable __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte type() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public int numBullet() { int o = __offset(6); return o != 0 ? bb.getInt(o + bb_pos) : 0; }

  public static int createGunItemTable(FlatBufferBuilder builder,
      byte type,
      int numBullet) {
    builder.startTable(2);
    GunItemTable.addNumBullet(builder, numBullet);
    GunItemTable.addType(builder, type);
    return GunItemTable.endGunItemTable(builder);
  }

  public static void startGunItemTable(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addType(FlatBufferBuilder builder, byte type) { builder.addByte(0, type, 0); }
  public static void addNumBullet(FlatBufferBuilder builder, int numBullet) { builder.addInt(1, numBullet, 0); }
  public static int endGunItemTable(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public GunItemTable get(int j) { return get(new GunItemTable(), j); }
    public GunItemTable get(GunItemTable obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

