// automatically generated by the FlatBuffers compiler, do not modify

package survival2d.flatbuffers;

public final class GunType {
  public static final byte NORMAL = 0;
  public static final String[] names = {
    "NORMAL",
  };

  private GunType() {}

  public static String name(int e) {
    return names[e];
  }
}
