// automatically generated by the FlatBuffers compiler, do not modify

package survival2d.flatbuffers;

public final class GunTypeEnum {
  private GunTypeEnum() { }
  public static final byte NORMAL = 0;

  public static final String[] names = { "NORMAL", };

  public static String name(int e) { return names[e]; }
}

