// automatically generated by the FlatBuffers compiler, do not modify

package survival2d.flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class HelmetItemTable extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_1_12_0(); }
  public static HelmetItemTable getRootAsHelmetItemTable(ByteBuffer _bb) { return getRootAsHelmetItemTable(_bb, new HelmetItemTable()); }
  public static HelmetItemTable getRootAsHelmetItemTable(ByteBuffer _bb, HelmetItemTable obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public HelmetItemTable __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte type() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) : 0; }

  public static int createHelmetItemTable(FlatBufferBuilder builder,
      byte type) {
    builder.startTable(1);
    HelmetItemTable.addType(builder, type);
    return HelmetItemTable.endHelmetItemTable(builder);
  }

  public static void startHelmetItemTable(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addType(FlatBufferBuilder builder, byte type) { builder.addByte(0, type, 0); }
  public static int endHelmetItemTable(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public HelmetItemTable get(int j) { return get(new HelmetItemTable(), j); }
    public HelmetItemTable get(HelmetItemTable obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

