// automatically generated by the FlatBuffers compiler, do not modify

package survival2d.flatbuffers;

public final class ItemUnion {
  private ItemUnion() { }
  public static final byte NONE = 0;
  public static final byte BulletItemTable = 1;
  public static final byte GunItemTable = 2;

  public static final String[] names = { "NONE", "BulletItemTable", "GunItemTable", };

  public static String name(int e) { return names[e]; }
}

