// automatically generated by the FlatBuffers compiler, do not modify

package survival2d.flatbuffers;

public final class ItemUnion {
  private ItemUnion() { }
  public static final byte NONE = 0;
  public static final byte BulletItemTable = 1;
  public static final byte GunItemTable = 2;
  public static final byte VestItemTable = 3;
  public static final byte HelmetItemTable = 4;
  public static final byte BandageItemTable = 5;
  public static final byte MedKitItemTable = 6;
  public static final byte BackPackItemTable = 7;

  public static final String[] names = { "NONE", "BulletItemTable", "GunItemTable", "VestItemTable", "HelmetItemTable", "BandageItemTable", "MedKitItemTable", "BackPackItemTable", };

  public static String name(int e) { return names[e]; }
}

