// automatically generated by the FlatBuffers compiler, do not modify

package survival2d.flatbuffers;

public final class Item {
  public static final byte NONE = 0;
  public static final byte BulletItem = 1;
  public static final byte GunItem = 2;
  public static final String[] names = {
    "NONE", "BulletItem", "GunItem",
  };

  private Item() {}

  public static String name(int e) {
    return names[e];
  }
}
