// automatically generated by the FlatBuffers compiler, do not modify

package survival2d.flatbuffers;

public final class MapObjectUnion {
  private MapObjectUnion() { }
  public static final byte NONE = 0;
  public static final byte BulletItemTable = 1;
  public static final byte VestItemTable = 2;
  public static final byte HelmetItemTable = 3;
  public static final byte BandageItemTable = 4;
  public static final byte MedKitItemTable = 5;
  public static final byte TreeTable = 6;
  public static final byte ContainerTable = 7;
  public static final byte StoneTable = 8;
  public static final byte WallTable = 9;
  public static final byte BulletTable = 10;

  public static final String[] names = { "NONE", "BulletItemTable", "VestItemTable", "HelmetItemTable", "BandageItemTable", "MedKitItemTable", "TreeTable", "ContainerTable", "StoneTable", "WallTable", "BulletTable", };

  public static String name(int e) { return names[e]; }
}

