// automatically generated by the FlatBuffers compiler, do not modify

package survival2d.flatbuffers;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Table;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class MapObject extends Table {
  public static void ValidateVersion() {
    Constants.FLATBUFFERS_1_12_0();
  }

  public static MapObject getRootAsMapObject(ByteBuffer _bb) {
    return getRootAsMapObject(_bb, new MapObject());
  }

  public static MapObject getRootAsMapObject(ByteBuffer _bb, MapObject obj) {
    _bb.order(ByteOrder.LITTLE_ENDIAN);
    return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb));
  }

  public static void startMapObject(FlatBufferBuilder builder) {
    builder.startTable(4);
  }

  public static void addId(FlatBufferBuilder builder, int id) {
    builder.addInt(0, id, 0);
  }

  public static void addPosition(FlatBufferBuilder builder, int positionOffset) {
    builder.addStruct(1, positionOffset, 0);
  }

  public static void addDataType(FlatBufferBuilder builder, byte dataType) {
    builder.addByte(2, dataType, 0);
  }

  public static void addData(FlatBufferBuilder builder, int dataOffset) {
    builder.addOffset(3, dataOffset, 0);
  }

  public static int endMapObject(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public void __init(int _i, ByteBuffer _bb) {
    __reset(_i, _bb);
  }

  public MapObject __assign(int _i, ByteBuffer _bb) {
    __init(_i, _bb);
    return this;
  }

  public int id() {
    int o = __offset(4);
    return o != 0 ? bb.getInt(o + bb_pos) : 0;
  }

  public survival2d.flatbuffers.Vec2 position() {
    return position(new survival2d.flatbuffers.Vec2());
  }

  public survival2d.flatbuffers.Vec2 position(survival2d.flatbuffers.Vec2 obj) {
    int o = __offset(6);
    return o != 0 ? obj.__assign(o + bb_pos, bb) : null;
  }

  public byte dataType() {
    int o = __offset(8);
    return o != 0 ? bb.get(o + bb_pos) : 0;
  }

  public Table data(Table obj) {
    int o = __offset(10);
    return o != 0 ? __union(obj, o + bb_pos) : null;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) {
      __reset(_vector, _element_size, _bb);
      return this;
    }

    public MapObject get(int j) {
      return get(new MapObject(), j);
    }

    public MapObject get(MapObject obj, int j) {
      return obj.__assign(__indirect(__element(j), bb), bb);
    }
  }
}
