// automatically generated by the FlatBuffers compiler, do not modify

package survival2d.flatbuffers;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Table;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class MatchInfoRequest extends Table {
  public static void ValidateVersion() {
    Constants.FLATBUFFERS_1_12_0();
  }

  public static MatchInfoRequest getRootAsMatchInfoRequest(ByteBuffer _bb) {
    return getRootAsMatchInfoRequest(_bb, new MatchInfoRequest());
  }

  public static MatchInfoRequest getRootAsMatchInfoRequest(ByteBuffer _bb, MatchInfoRequest obj) {
    _bb.order(ByteOrder.LITTLE_ENDIAN);
    return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb));
  }

  public static void startMatchInfoRequest(FlatBufferBuilder builder) {
    builder.startTable(0);
  }

  public static int endMatchInfoRequest(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public void __init(int _i, ByteBuffer _bb) {
    __reset(_i, _bb);
  }

  public MatchInfoRequest __assign(int _i, ByteBuffer _bb) {
    __init(_i, _bb);
    return this;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) {
      __reset(_vector, _element_size, _bb);
      return this;
    }

    public MatchInfoRequest get(int j) {
      return get(new MatchInfoRequest(), j);
    }

    public MatchInfoRequest get(MatchInfoRequest obj, int j) {
      return obj.__assign(__indirect(__element(j), bb), bb);
    }
  }
}
