// automatically generated by the FlatBuffers compiler, do not modify

package survival2d.flatbuffers;

public final class Obstacle {
  private Obstacle() { }
  public static final byte NONE = 0;
  public static final byte Tree = 1;
  public static final byte Container = 2;

  public static final String[] names = { "NONE", "Tree", "Container", };

  public static String name(int e) { return names[e]; }
}

