// automatically generated by the FlatBuffers compiler, do not modify

package survival2d.flatbuffers;

public final class PacketData {
  private PacketData() { }
  public static final byte NONE = 0;
  public static final byte MatchInfoResponse = 1;
  public static final byte PlayerMoveRequest = 2;
  public static final byte PlayerMoveResponse = 3;
  public static final byte PlayerAttackRequest = 4;
  public static final byte PlayerAttackResponse = 5;

  public static final String[] names = { "NONE", "MatchInfoResponse", "PlayerMoveRequest", "PlayerMoveResponse", "PlayerAttackRequest", "PlayerAttackResponse", };

  public static String name(int e) { return names[e]; }
}

