// automatically generated by the FlatBuffers compiler, do not modify

package survival2d.flatbuffers;

public final class PacketData {
  private PacketData() { }
  public static final byte NONE = 0;
  public static final byte MatchInfoRequest = 1;
  public static final byte MatchInfoResponse = 2;
  public static final byte PlayerMoveRequest = 3;
  public static final byte PlayerMoveResponse = 4;
  public static final byte PlayerAttackRequest = 5;
  public static final byte PlayerAttackResponse = 6;
  public static final byte PlayerInfoResponse = 7;
  public static final byte CreateBulletOnMapResponse = 8;
  public static final byte CreateItemOnMapResponse = 9;
  public static final byte ObstacleTakeDamageResponse = 10;
  public static final byte ObstacleDestroyResponse = 11;
  public static final byte PlayerTakeDamageResponse = 12;
  public static final byte PlayerDeadResponse = 13;
  public static final byte PlayerReloadWeaponRequest = 14;
  public static final byte PlayerReloadWeaponResponse = 15;
  public static final byte PlayerChangeWeaponRequest = 16;
  public static final byte PlayerChangeWeaponResponse = 17;
  public static final byte PlayerTakeItemRequest = 18;
  public static final byte PlayerTakeItemResponse = 19;
  public static final byte StartGameResponse = 20;
  public static final byte EndGameResponse = 21;
  public static final byte NewSafeZoneResponse = 22;
  public static final byte SafeZoneMoveResponse = 23;
  public static final byte PingRequest = 24;
  public static final byte PingResponse = 25;
  public static final byte PingByPlayerMoveRequest = 26;
  public static final byte PingByPlayerMoveResponse = 27;
  public static final byte PingByMatchInfoRequest = 28;
  public static final byte PingByMatchInfoResponse = 29;
  public static final byte UseHealItemRequest = 30;
  public static final byte UseHealItemResponse = 31;
  public static final byte SetAutoPlayRequest = 32;

  public static final String[] names = { "NONE", "MatchInfoRequest", "MatchInfoResponse", "PlayerMoveRequest", "PlayerMoveResponse", "PlayerAttackRequest", "PlayerAttackResponse", "PlayerInfoResponse", "CreateBulletOnMapResponse", "CreateItemOnMapResponse", "ObstacleTakeDamageResponse", "ObstacleDestroyResponse", "PlayerTakeDamageResponse", "PlayerDeadResponse", "PlayerReloadWeaponRequest", "PlayerReloadWeaponResponse", "PlayerChangeWeaponRequest", "PlayerChangeWeaponResponse", "PlayerTakeItemRequest", "PlayerTakeItemResponse", "StartGameResponse", "EndGameResponse", "NewSafeZoneResponse", "SafeZoneMoveResponse", "PingRequest", "PingResponse", "PingByPlayerMoveRequest", "PingByPlayerMoveResponse", "PingByMatchInfoRequest", "PingByMatchInfoResponse", "UseHealItemRequest", "UseHealItemResponse", "SetAutoPlayRequest", };

  public static String name(int e) { return names[e]; }
}

