// automatically generated by the FlatBuffers compiler, do not modify

package survival2d.flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class PingByPlayerMoveRequest extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_1_12_0(); }
  public static PingByPlayerMoveRequest getRootAsPingByPlayerMoveRequest(ByteBuffer _bb) { return getRootAsPingByPlayerMoveRequest(_bb, new PingByPlayerMoveRequest()); }
  public static PingByPlayerMoveRequest getRootAsPingByPlayerMoveRequest(ByteBuffer _bb, PingByPlayerMoveRequest obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public PingByPlayerMoveRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public survival2d.flatbuffers.Vec2 direction() { return direction(new survival2d.flatbuffers.Vec2()); }
  public survival2d.flatbuffers.Vec2 direction(survival2d.flatbuffers.Vec2 obj) { int o = __offset(4); return o != 0 ? obj.__assign(o + bb_pos, bb) : null; }
  public double rotation() { int o = __offset(6); return o != 0 ? bb.getDouble(o + bb_pos) : 0.0; }

  public static void startPingByPlayerMoveRequest(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addDirection(FlatBufferBuilder builder, int directionOffset) { builder.addStruct(0, directionOffset, 0); }
  public static void addRotation(FlatBufferBuilder builder, double rotation) { builder.addDouble(1, rotation, 0.0); }
  public static int endPingByPlayerMoveRequest(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public PingByPlayerMoveRequest get(int j) { return get(new PingByPlayerMoveRequest(), j); }
    public PingByPlayerMoveRequest get(PingByPlayerMoveRequest obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

