// automatically generated by the FlatBuffers compiler, do not modify

package survival2d.flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class PingByPlayerMoveResponse extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_1_12_0(); }
  public static PingByPlayerMoveResponse getRootAsPingByPlayerMoveResponse(ByteBuffer _bb) { return getRootAsPingByPlayerMoveResponse(_bb, new PingByPlayerMoveResponse()); }
  public static PingByPlayerMoveResponse getRootAsPingByPlayerMoveResponse(ByteBuffer _bb, PingByPlayerMoveResponse obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public PingByPlayerMoveResponse __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int playerId() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public survival2d.flatbuffers.Vector2Struct position() { return position(new survival2d.flatbuffers.Vector2Struct()); }
  public survival2d.flatbuffers.Vector2Struct position(survival2d.flatbuffers.Vector2Struct obj) { int o = __offset(6); return o != 0 ? obj.__assign(o + bb_pos, bb) : null; }
  public double rotation() { int o = __offset(8); return o != 0 ? bb.getDouble(o + bb_pos) : 0.0; }

  public static void startPingByPlayerMoveResponse(FlatBufferBuilder builder) { builder.startTable(3); }
  public static void addPlayerId(FlatBufferBuilder builder, int playerId) { builder.addInt(0, playerId, 0); }
  public static void addPosition(FlatBufferBuilder builder, int positionOffset) { builder.addStruct(1, positionOffset, 0); }
  public static void addRotation(FlatBufferBuilder builder, double rotation) { builder.addDouble(2, rotation, 0.0); }
  public static int endPingByPlayerMoveResponse(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public PingByPlayerMoveResponse get(int j) { return get(new PingByPlayerMoveResponse(), j); }
    public PingByPlayerMoveResponse get(PingByPlayerMoveResponse obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

