// automatically generated by the FlatBuffers compiler, do not modify

package survival2d.flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class PlayerAttackResponse extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_1_12_0(); }
  public static PlayerAttackResponse getRootAsPlayerAttackResponse(ByteBuffer _bb) { return getRootAsPlayerAttackResponse(_bb, new PlayerAttackResponse()); }
  public static PlayerAttackResponse getRootAsPlayerAttackResponse(ByteBuffer _bb, PlayerAttackResponse obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public PlayerAttackResponse __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void startPlayerAttackResponse(FlatBufferBuilder builder) { builder.startTable(0); }
  public static int endPlayerAttackResponse(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public PlayerAttackResponse get(int j) { return get(new PlayerAttackResponse(), j); }
    public PlayerAttackResponse get(PlayerAttackResponse obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

