// automatically generated by the FlatBuffers compiler, do not modify

package survival2d.flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class PlayerMoveRequest extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_1_12_0(); }
  public static PlayerMoveRequest getRootAsPlayerMoveRequest(ByteBuffer _bb) { return getRootAsPlayerMoveRequest(_bb, new PlayerMoveRequest()); }
  public static PlayerMoveRequest getRootAsPlayerMoveRequest(ByteBuffer _bb, PlayerMoveRequest obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public PlayerMoveRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public survival2d.flatbuffers.Vector2Struct direction() { return direction(new survival2d.flatbuffers.Vector2Struct()); }
  public survival2d.flatbuffers.Vector2Struct direction(survival2d.flatbuffers.Vector2Struct obj) { int o = __offset(4); return o != 0 ? obj.__assign(o + bb_pos, bb) : null; }
  public float rotation() { int o = __offset(6); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }

  public static void startPlayerMoveRequest(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addDirection(FlatBufferBuilder builder, int directionOffset) { builder.addStruct(0, directionOffset, 0); }
  public static void addRotation(FlatBufferBuilder builder, float rotation) { builder.addFloat(1, rotation, 0.0f); }
  public static int endPlayerMoveRequest(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public PlayerMoveRequest get(int j) { return get(new PlayerMoveRequest(), j); }
    public PlayerMoveRequest get(PlayerMoveRequest obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

