// automatically generated by the FlatBuffers compiler, do not modify

package survival2d.flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class PlayerTakeItemResponse extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_1_12_0(); }
  public static PlayerTakeItemResponse getRootAsPlayerTakeItemResponse(ByteBuffer _bb) { return getRootAsPlayerTakeItemResponse(_bb, new PlayerTakeItemResponse()); }
  public static PlayerTakeItemResponse getRootAsPlayerTakeItemResponse(ByteBuffer _bb, PlayerTakeItemResponse obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public PlayerTakeItemResponse __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int playerId() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int itemOnMapId() { int o = __offset(6); return o != 0 ? bb.getInt(o + bb_pos) : 0; }

  public static int createPlayerTakeItemResponse(FlatBufferBuilder builder,
      int playerId,
      int itemOnMapId) {
    builder.startTable(2);
    PlayerTakeItemResponse.addItemOnMapId(builder, itemOnMapId);
    PlayerTakeItemResponse.addPlayerId(builder, playerId);
    return PlayerTakeItemResponse.endPlayerTakeItemResponse(builder);
  }

  public static void startPlayerTakeItemResponse(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addPlayerId(FlatBufferBuilder builder, int playerId) { builder.addInt(0, playerId, 0); }
  public static void addItemOnMapId(FlatBufferBuilder builder, int itemOnMapId) { builder.addInt(1, itemOnMapId, 0); }
  public static int endPlayerTakeItemResponse(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public PlayerTakeItemResponse get(int j) { return get(new PlayerTakeItemResponse(), j); }
    public PlayerTakeItemResponse get(PlayerTakeItemResponse obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

