// automatically generated by the FlatBuffers compiler, do not modify

package survival2d.flatbuffers;

public final class RequestUnion {
  private RequestUnion() { }
  public static final byte NONE = 0;
  public static final byte MatchInfoRequest = 1;
  public static final byte PlayerMoveRequest = 2;
  public static final byte PlayerAttackRequest = 3;
  public static final byte PlayerReloadWeaponRequest = 4;
  public static final byte PlayerChangeWeaponRequest = 5;
  public static final byte PlayerTakeItemRequest = 6;
  public static final byte PingRequest = 7;
  public static final byte PingByPlayerMoveRequest = 8;
  public static final byte PingByMatchInfoRequest = 9;

  public static final String[] names = { "NONE", "MatchInfoRequest", "PlayerMoveRequest", "PlayerAttackRequest", "PlayerReloadWeaponRequest", "PlayerChangeWeaponRequest", "PlayerTakeItemRequest", "PingRequest", "PingByPlayerMoveRequest", "PingByMatchInfoRequest", };

  public static String name(int e) { return names[e]; }
}

