// automatically generated by the FlatBuffers compiler, do not modify

package survival2d.flatbuffers;

public final class ResponseErrorEnum {
  private ResponseErrorEnum() { }
  public static final byte SUCCESS = 0;
  public static final byte TEAM_NOT_FOUND = 1;
  public static final byte JOIN_TEAM_ERROR = 2;
  public static final byte NOT_FOUND_YET = 3;
  public static final byte UNKNOWN = 4;

  public static final String[] names = { "SUCCESS", "TEAM_NOT_FOUND", "JOIN_TEAM_ERROR", "NOT_FOUND_YET", "UNKNOWN", };

  public static String name(int e) { return names[e]; }
}

