// automatically generated by the FlatBuffers compiler, do not modify

package survival2d.flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class SetAutoPlayResponse extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_1_12_0(); }
  public static SetAutoPlayResponse getRootAsSetAutoPlayResponse(ByteBuffer _bb) { return getRootAsSetAutoPlayResponse(_bb, new SetAutoPlayResponse()); }
  public static SetAutoPlayResponse getRootAsSetAutoPlayResponse(ByteBuffer _bb, SetAutoPlayResponse obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public SetAutoPlayResponse __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public boolean enable() { int o = __offset(4); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }

  public static int createSetAutoPlayResponse(FlatBufferBuilder builder,
      boolean enable) {
    builder.startTable(1);
    SetAutoPlayResponse.addEnable(builder, enable);
    return SetAutoPlayResponse.endSetAutoPlayResponse(builder);
  }

  public static void startSetAutoPlayResponse(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addEnable(FlatBufferBuilder builder, boolean enable) { builder.addBoolean(0, enable, false); }
  public static int endSetAutoPlayResponse(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public SetAutoPlayResponse get(int j) { return get(new SetAutoPlayResponse(), j); }
    public SetAutoPlayResponse get(SetAutoPlayResponse obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

