// automatically generated by the FlatBuffers compiler, do not modify

package survival2d.flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class UseHealItemRequest extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_1_12_0(); }
  public static UseHealItemRequest getRootAsUseHealItemRequest(ByteBuffer _bb) { return getRootAsUseHealItemRequest(_bb, new UseHealItemRequest()); }
  public static UseHealItemRequest getRootAsUseHealItemRequest(ByteBuffer _bb, UseHealItemRequest obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public UseHealItemRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte typeType() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public Table type(Table obj) { int o = __offset(6); return o != 0 ? __union(obj, o + bb_pos) : null; }

  public static int createUseHealItemRequest(FlatBufferBuilder builder,
      byte type_type,
      int typeOffset) {
    builder.startTable(2);
    UseHealItemRequest.addType(builder, typeOffset);
    UseHealItemRequest.addTypeType(builder, type_type);
    return UseHealItemRequest.endUseHealItemRequest(builder);
  }

  public static void startUseHealItemRequest(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addTypeType(FlatBufferBuilder builder, byte typeType) { builder.addByte(0, typeType, 0); }
  public static void addType(FlatBufferBuilder builder, int typeOffset) { builder.addOffset(1, typeOffset, 0); }
  public static int endUseHealItemRequest(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public UseHealItemRequest get(int j) { return get(new UseHealItemRequest(), j); }
    public UseHealItemRequest get(UseHealItemRequest obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

