// automatically generated by the FlatBuffers compiler, do not modify

package survival2d.flatbuffers;

public final class VestType {
  private VestType() { }
  public static final byte LEVEL_0 = 0;
  public static final byte LEVEL_1 = 1;

  public static final String[] names = { "LEVEL_0", "LEVEL_1", };

  public static String name(int e) { return names[e]; }
}

