// automatically generated by the FlatBuffers compiler, do not modify

package survival2d.flatbuffers;

public final class WeaponData {
  public static final byte NONE = 0;
  public static final byte Hand = 1;
  public static final byte Gun = 2;
  public static final String[] names = {
    "NONE", "Hand", "Gun",
  };

  private WeaponData() {}

  public static String name(int e) {
    return names[e];
  }
}
