// automatically generated by the FlatBuffers compiler, do not modify

package survival2d.flatbuffers;

public final class WeaponUnion {
  private WeaponUnion() { }
  public static final byte NONE = 0;
  public static final byte HandTable = 1;
  public static final byte GunTable = 2;

  public static final String[] names = { "NONE", "HandTable", "GunTable", };

  public static String name(int e) { return names[e]; }
}

