@startuml

title __SERIALIZE's Class Diagram__\n

  namespace survival2d {
    namespace util {
      namespace serialize {
        class survival2d.util.serialize.EnumSerializer {
            {static} - instance : EnumSerializer
            {static} - log : Logger
            {static} + getInstance()
            + serialize()
        }
      }
    }
  }
  

  namespace survival2d {
    namespace util {
      namespace serialize {
        class survival2d.util.serialize.ExcludeAnnotationFromGsonStrategy {
            {static} + getInstance()
            + shouldSkipClass()
            + shouldSkipField()
        }
      }
    }
  }
  

  namespace survival2d {
    namespace util {
      namespace serialize {
        class survival2d.util.serialize.ExcludeAnnotationFromGsonStrategy.InstanceHolder {
            {static} - instance : ExcludeAnnotationFromGsonStrategy
        }
      }
    }
  }
  

  namespace survival2d {
    namespace util {
      namespace serialize {
        interface survival2d.util.serialize.ExcludeFromGson {
        }
      }
    }
  }
  

  namespace survival2d {
    namespace util {
      namespace serialize {
        class survival2d.util.serialize.GsonHolder {
            {static} - enablePostProcess : Gson
            {static} - exposedGson : Gson
            {static} - normalGson : Gson
            {static} - responseGson : Gson
            {static} - withExcludeAnnotation : Gson
            {static} + getEnablePostProcess()
            {static} + getExposedGson()
            {static} + getNormalGson()
            {static} + getResponseGson()
            {static} + getWithExcludeAnnotation()
        }
      }
    }
  }
  

  namespace survival2d {
    namespace util {
      namespace serialize {
        interface survival2d.util.serialize.PostProcessable {
            {abstract} + postProcess()
        }
      }
    }
  }
  

  namespace survival2d {
    namespace util {
      namespace serialize {
        class survival2d.util.serialize.PostProcessingEnabler {
            {static} - instance : PostProcessingEnabler
            + create()
            {static} + getInstance()
        }
      }
    }
  }
  

  survival2d.util.serialize.EnumSerializer .up.|> com.google.gson.JsonSerializer
  survival2d.util.serialize.ExcludeAnnotationFromGsonStrategy .up.|> com.google.gson.ExclusionStrategy
  survival2d.util.serialize.ExcludeAnnotationFromGsonStrategy +-down- survival2d.util.serialize.ExcludeAnnotationFromGsonStrategy.InstanceHolder
  survival2d.util.serialize.PostProcessingEnabler .up.|> com.google.gson.TypeAdapterFactory


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
