@startuml

title __BASE's Class Diagram__\n

  namespace survival2d {
    namespace match.entity.base {
      class survival2d.match.entity.base.Circle {
          - radius : double
          + Circle()
          + equals()
          + getRadius()
          + hashCode()
          + toString()
      }
    }
  }
  

  namespace survival2d {
    namespace match.entity.base {
      interface survival2d.match.entity.base.Containable {
          {abstract} + getItems()
      }
    }
  }
  

  namespace survival2d {
    namespace match.entity.base {
      interface survival2d.match.entity.base.Destroyable {
          {abstract} + isDestroyed()
          + markDestroyed()
          {abstract} + setDestroyed()
      }
    }
  }
  

  namespace survival2d {
    namespace match.entity.base {
      class survival2d.match.entity.base.Dot {
          + toString()
      }
    }
  }
  

  namespace survival2d {
    namespace match.entity.base {
      interface survival2d.match.entity.base.HasHp {
          {abstract} + getHp()
          + isAlive()
          + isDestroyed()
          + reduceHp()
          {abstract} + setHp()
      }
    }
  }
  

  namespace survival2d {
    namespace match.entity.base {
      interface survival2d.match.entity.base.HasId {
          {abstract} + getId()
          {abstract} + setId()
      }
    }
  }
  

  namespace survival2d {
    namespace match.entity.base {
      interface survival2d.match.entity.base.HasPosition {
          {abstract} + getPosition()
          {abstract} + setPosition()
      }
    }
  }
  

  namespace survival2d {
    namespace match.entity.base {
      interface survival2d.match.entity.base.HasShape {
          {abstract} + getShape()
      }
    }
  }
  

  namespace survival2d {
    namespace match.entity.base {
      interface survival2d.match.entity.base.Item {
          {abstract} + getItemType()
      }
    }
  }
  

  namespace survival2d {
    namespace match.entity.base {
      interface survival2d.match.entity.base.MapObject {
      }
    }
  }
  

  namespace survival2d {
    namespace match.entity.base {
      interface survival2d.match.entity.base.Movable {
          + moveBy()
          + moveTo()
      }
    }
  }
  

  namespace survival2d {
    namespace match.entity.base {
      class survival2d.match.entity.base.Rectangle {
          - height : double
          - width : double
          + Rectangle()
          + equals()
          + getHeight()
          + getWidth()
          + hashCode()
          + toString()
      }
    }
  }
  

  namespace survival2d {
    namespace match.entity.base {
      interface survival2d.match.entity.base.Shape {
      }
    }
  }
  

  survival2d.match.entity.base.Circle .up.|> survival2d.match.entity.base.Shape
  survival2d.match.entity.base.Dot .up.|> survival2d.match.entity.base.Shape
  survival2d.match.entity.base.Rectangle .up.|> survival2d.match.entity.base.Shape


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
