// automatically generated by the FlatBuffers compiler, do not modify

package com.survival2d.server.flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Obstacle extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_1_12_0(); }
  public static Obstacle getRootAsObstacle(ByteBuffer _bb) { return getRootAsObstacle(_bb, new Obstacle()); }
  public static Obstacle getRootAsObstacle(ByteBuffer _bb, Obstacle obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Obstacle __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public com.survival2d.server.flatbuffers.Vec3 pos() { return pos(new com.survival2d.server.flatbuffers.Vec3()); }
  public com.survival2d.server.flatbuffers.Vec3 pos(com.survival2d.server.flatbuffers.Vec3 obj) { int o = __offset(4); return o != 0 ? obj.__assign(o + bb_pos, bb) : null; }

  public static void startObstacle(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addPos(FlatBufferBuilder builder, int posOffset) { builder.addStruct(0, posOffset, 0); }
  public static int endObstacle(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
  public static void finishObstacleBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedObstacleBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Obstacle get(int j) { return get(new Obstacle(), j); }
    public Obstacle get(Obstacle obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

