@startuml

title __NETWORK's Class Diagram__\n

  namespace survival2d {
    namespace match.network {
      class survival2d.match.network.MatchCommand {
          {static} + CREATE_BULLET : String
          {static} + CREATE_ITEM : String
          {static} + DROP_ITEM : String
          {static} + END_GAME : String
          {static} + GAME_INFO : String
          {static} + GAME_START : String
          {static} + MATCH_INFO : String
          {static} + MATCH_START : String
          {static} + OBSTACLE_DESTROYED : String
          {static} + OBSTACLE_TAKE_DAMAGE : String
          {static} + PLAYER_ATTACK : String
          {static} + PLAYER_CHANGE_WEAPON : String
          {static} + PLAYER_DEAD : String
          {static} + PLAYER_MOVE : String
          {static} + PLAYER_RELOAD : String
          {static} + PLAYER_TAKE_DAMAGE : String
          {static} + TAKE_ITEM : String
      }
    }
  }
  

  namespace survival2d {
    namespace match.network {
      class survival2d.match.network.MatchRequestController {
          {static} - log : Logger
          - responseFactory : EzyResponseFactory
          + handleDropItem()
          + handleMatchInfo()
          + handlePlayerAttack()
          + handlePlayerChangeWeapon()
          + handlePlayerMove()
          + handlePlayerReload()
          + handleTakeItem()
      }
    }
  }
  

  survival2d.match.network.MatchRequestController o-- survival2d.service.MatchingService : matchingService


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
