@startuml

title __REQUEST's Class Diagram__\n

  namespace survival2d {
    namespace match.network {
      namespace request {
        class survival2d.match.network.request.MatchInfoRequest {
            - matchId : long
            + MatchInfoRequest()
            + equals()
            + getMatchId()
            + hashCode()
            + setMatchId()
            + toString()
            # canEqual()
        }
      }
    }
  }
  

  namespace survival2d {
    namespace match.network {
      namespace request {
        class survival2d.match.network.request.PlayerAttackRequest {
            - direction : Vector2D
            + PlayerAttackRequest()
            + equals()
            + getDirection()
            + hashCode()
            + setDirection()
            + toString()
            # canEqual()
        }
      }
    }
  }
  

  namespace survival2d {
    namespace match.network {
      namespace request {
        class survival2d.match.network.request.PlayerChangeWeaponRequest {
            - slot : int
            + PlayerChangeWeaponRequest()
            + equals()
            + getSlot()
            + hashCode()
            + setSlot()
            + toString()
            # canEqual()
        }
      }
    }
  }
  

  namespace survival2d {
    namespace match.network {
      namespace request {
        class survival2d.match.network.request.PlayerDropItemRequest {
            ~ itemId : String
            + PlayerDropItemRequest()
            + equals()
            + getItemId()
            + hashCode()
            + setItemId()
            + toString()
            # canEqual()
        }
      }
    }
  }
  

  namespace survival2d {
    namespace match.network {
      namespace request {
        class survival2d.match.network.request.PlayerDropItemRequest.RequestReader {
            + read()
        }
      }
    }
  }
  

  namespace survival2d {
    namespace match.network {
      namespace request {
        class survival2d.match.network.request.PlayerMoveRequest {
            ~ direction : Vector2D
            ~ rotation : double
            + PlayerMoveRequest()
            + equals()
            + getDirection()
            + getRotation()
            + hashCode()
            + setDirection()
            + setRotation()
            + toString()
            # canEqual()
        }
      }
    }
  }
  

  namespace survival2d {
    namespace match.network {
      namespace request {
        class survival2d.match.network.request.PlayerMoveRequest.PlayerMoveRequestReader {
            + read()
        }
      }
    }
  }
  

  survival2d.match.network.request.PlayerDropItemRequest +-down- survival2d.match.network.request.PlayerDropItemRequest.RequestReader
  survival2d.match.network.request.PlayerDropItemRequest.RequestReader .up.|> com.tvd12.ezyfox.binding.EzyReader
  survival2d.match.network.request.PlayerMoveRequest +-down- survival2d.match.network.request.PlayerMoveRequest.PlayerMoveRequestReader
  survival2d.match.network.request.PlayerMoveRequest.PlayerMoveRequestReader .up.|> com.tvd12.ezyfox.binding.EzyReader


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
