@startuml

title __RESPONSE's Class Diagram__\n

  namespace survival2d {
    namespace misc {
      namespace response {
        class survival2d.misc.response.PingByPlayerMoveResponse {
            ~ position : Vector2D
            ~ rotation : double
            ~ username : String
            {static} - log : Logger
            {static} + builder()
            + equals()
            + getPosition()
            + getRotation()
            + getUsername()
            + hashCode()
            + setPosition()
            + setRotation()
            + setUsername()
            + toString()
            # canEqual()
            ~ PingByPlayerMoveResponse()
        }
      }
    }
  }
  

  namespace survival2d {
    namespace misc {
      namespace response {
        class survival2d.misc.response.PingByPlayerMoveResponse.PingByPlayerMoveResponseBuilder {
            - position : Vector2D
            - rotation : double
            - username : String
            + build()
            + position()
            + rotation()
            + toString()
            + username()
            ~ PingByPlayerMoveResponseBuilder()
        }
      }
    }
  }
  

  namespace survival2d {
    namespace misc {
      namespace response {
        class survival2d.misc.response.PingByPlayerMoveResponse.ResponseWriter {
            + write()
        }
      }
    }
  }
  

  survival2d.misc.response.PingByPlayerMoveResponse +-down- survival2d.misc.response.PingByPlayerMoveResponse.PingByPlayerMoveResponseBuilder
  survival2d.misc.response.PingByPlayerMoveResponse +-down- survival2d.misc.response.PingByPlayerMoveResponse.ResponseWriter
  survival2d.misc.response.PingByPlayerMoveResponse.ResponseWriter .up.|> com.tvd12.ezyfox.binding.EzyWriter


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
